webtalk_init -webtalk_dir E:\\Users\\Q\\lab1v\\lab1v.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期二 四月 7 13:53:51 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "omt4t3hlceb54so5jhbgsu7bme" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1428385036341" -context "sdk\\\\hardware/1428385036341"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1428385036341"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1428385036341"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1428385036341"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1428385036341"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1428385036341"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1428385036341"
webtalk_add_data -client sdk -key uid -value "1428385095309" -context "sdk\\\\bsp/1428385095309"
webtalk_add_data -client sdk -key hwid -value "1428385036341" -context "sdk\\\\bsp/1428385095309"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1428385095309"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\bsp/1428385095309"
webtalk_add_data -client sdk -key uid -value "1428385106991" -context "sdk\\\\application/1428385106991"
webtalk_add_data -client sdk -key hwid -value "1428385036341" -context "sdk\\\\application/1428385106991"
webtalk_add_data -client sdk -key bspid -value "1428385095309" -context "sdk\\\\application/1428385106991"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1428385106991"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1428385106991"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\application/1428385106991"
webtalk_transmit -clientid 836964009 -regid "" -xml E:\\Users\\Q\\lab1v\\lab1v.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\Users\\Q\\lab1v\\lab1v.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\Users\\Q\\lab1v\\lab1v.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
